export const laptopSpecs = [
    {
        name:"Asus ROG Strix G17",
        cpuName:"Processor:",
        cpu:"Ryzen 9 5900HX",
        ramName:"RAM:",
        ram:"16GB DDR4 3200Mhz",
        storageName:"Storage:",
        storage:"500 GB PCIe SSD",
        gpuName:"Graphics Card:",
        gpu:"Nvidia RTX 3050",
        osName:"Operating System:",
        os:"Windows 10",
        cameraName:"Camera:",
        camera:"720P HD camera",
        portName:"Ports:",
        ports:"1x 3.5mm Combo Audio Jack, 1x HDMI 2.0, 1x USB 2.0 Type-A",
        wifiName:"Wifi:",
        wifi:"Wi-Fi 5 (802.11ac)+Bluetooth 5.0 (Dual band) 2*2;(*BT version may change with OS upgrades.)",
        battName:"Battery:",
        battery:"48WHrs, 3S1P, 3-cell Li-ion",
        weightName:"Weight:",
        weight:"2.20 Kg (4.85 lbs)"
    },
    {
        name:"",
        cpu:"",
        ram:"",
        storage:"",
        gpu:"",
        os:"Windows 10",
        camera:"720P HD camera",
        ports:"1x 3.5mm Combo Audio Jack, 1x HDMI 2.0, 1x USB 2.0 Type-A",
        wifi:"Wi-Fi 5 (802.11ac)+Bluetooth 5.0 (Dual band) 2*2;(*BT version may change with OS upgrades.)",
        battery:"48WHrs, 3S1P, 3-cell Li-ion",
        weight:"2.20 Kg (4.85 lbs)"
    },
    {
        name:"",
        cpu:"",
        ram:"",
        storage:"",
        gpu:"",
        os:"Windows 10",
        camera:"720P HD camera",
        ports:"1x 3.5mm Combo Audio Jack, 1x HDMI 2.0, 1x USB 2.0 Type-A",
        wifi:"Wi-Fi 5 (802.11ac)+Bluetooth 5.0 (Dual band) 2*2;(*BT version may change with OS upgrades.)",
        battery:"48WHrs, 3S1P, 3-cell Li-ion",
        weight:"2.20 Kg (4.85 lbs)"
    },
    {
        name:"",
        cpu:"",
        ram:"",
        storage:"",
        gpu:"",
        os:"Windows 10",
        camera:"720P HD camera",
        ports:"1x 3.5mm Combo Audio Jack, 1x HDMI 2.0, 1x USB 2.0 Type-A",
        wifi:"Wi-Fi 5 (802.11ac)+Bluetooth 5.0 (Dual band) 2*2;(*BT version may change with OS upgrades.)",
        battery:"48WHrs, 3S1P, 3-cell Li-ion",
        weight:"2.20 Kg (4.85 lbs)"
    },
    {
        name:"",
        cpu:"",
        ram:"",
        storage:"",
        gpu:"",
        os:"Windows 10",
        camera:"720P HD camera",
        ports:"1x 3.5mm Combo Audio Jack, 1x HDMI 2.0, 1x USB 2.0 Type-A",
        wifi:"Wi-Fi 5 (802.11ac)+Bluetooth 5.0 (Dual band) 2*2;(*BT version may change with OS upgrades.)",
        battery:"48WHrs, 3S1P, 3-cell Li-ion",
        weight:"2.20 Kg (4.85 lbs)"
    },
    {
        name:"",
        cpu:"",
        ram:"",
        storage:"",
        gpu:"",
        os:"Windows 10",
        camera:"720P HD camera",
        ports:"1x 3.5mm Combo Audio Jack, 1x HDMI 2.0, 1x USB 2.0 Type-A",
        wifi:"Wi-Fi 5 (802.11ac)+Bluetooth 5.0 (Dual band) 2*2;(*BT version may change with OS upgrades.)",
        battery:"48WHrs, 3S1P, 3-cell Li-ion",
        weight:"2.20 Kg (4.85 lbs)"
    },
    {
        name:"",
        cpu:"",
        ram:"",
        storage:"",
        gpu:"",
        os:"Windows 10",
        camera:"720P HD camera",
        ports:"1x 3.5mm Combo Audio Jack, 1x HDMI 2.0, 1x USB 2.0 Type-A",
        wifi:"Wi-Fi 5 (802.11ac)+Bluetooth 5.0 (Dual band) 2*2;(*BT version may change with OS upgrades.)",
        battery:"48WHrs, 3S1P, 3-cell Li-ion",
        weight:"2.20 Kg (4.85 lbs)"
    },
]